<?php
/*
* @file
* Display a Summary of your Drupal Installation.
*/
/**
* Implementation of hook_help()
*/
function summary_help($path, $arg) {
	switch ($path) {
		case 'admin/help#summary':
				return '<p>' . t('Sample Summary module from Atelier Drupal book. This module
provide a summary page of your Drupal Installation.') . '</p>';
	}
}

/*
* Implementation of hook_menu()
*/
function summary_menu() {
	/*
	 * The page
	 */
	$items['summary'] = array(
			'title' => 'Summary of your site',
			'access arguments' => array(true),
			'type' => MENU_CALLBACK,
			'page callback' => 'summary_content',
	);
	/*
	 * Administration interface
	 */
	$items['admin/config/system/summary'] = array(
			'title' => t('Summary settings'),
			'description' => t('Summary configuration page'),
			'page callback' => 'drupal_get_form',
			'page arguments' => array('summary_admin_settings'),
			'access arguments' => array('administer site configuration'),
			'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}
/*
* Content of the summary page
*/
function summary_content(){
	//List of all activated modules
	$summary_module_list = module_list();
	$summary_module_list = t('<h3>List of all activated modules</h3>') .
implode($summary_module_list,', ');
	$output = $summary_module_list;
	
	// List of vocabularies
	$summary_vocabularies = taxonomy_get_vocabularies();
	$summary_vocabularies_list='';
	foreach ($summary_vocabularies as $vocab){
		$summary_vocabularies_list .= $vocab->name . ',';
	}
	$summary_vocabularies_list = t('<h3>Vocabularies</h3>') . $summary_vocabularies_list;
	$output .= $summary_vocabularies_list;
	
	$summary_node_types = node_type_get_types();
	$node_type_list = '';
	foreach ($summary_node_types as $node_type) {
		$node_type_list .= $node_type->name . ',';
	}
	$output .= t('<h3>Node types</h3>') . $node_type_list;
	return $output;
}

/*
 * Define the adminsitration form
 * for information : http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html
*/
function summary_admin_settings(){
	$form['summary_display'] = array(
			'#type' => 'checkboxes',
			'#title' => t('Sections of the summary'),
			'#description' => t('Check the sections to show in the summary page'),
			'#options' => array('module' => t('Module list'), 'vocabulary' =>
					t('Vocabulary list'), 'content_type' => t('Content types')),
	);
	return system_settings_form($form);;
}