<?php
/**
 * @file
* Display a Hello World block
 * bla
*/

/**
* Implementation of hook_block_info()
*/

function hello_block_info() {
$block['hello-block'] = array(
'info' => 'Hello world ! Where are you? Im here and there and there',
);
return $block;
}

/**
 * Implementation of hook_block_view()
 */
function hello_block_view($delta = '') {
	$block = array(
			'subject' => t('My First module says the following'),
			'content' => t('Hello World !!!')


	);
        if(FALSE) {
        
        }
	return $block;

}

/**
 * Implementation of hook_help()
 */
function hello_help($path, $arg) {
	switch ($path) {
		case 'admin/help#hello':
			return '<p>' . t('Sample module from Atelier Drupal book. This module
just provide a hello world block.') . '</p>';
	}
}